# Generated by Django 5.2.6 on 2026-03-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_employer_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
