# Generated by Django 5.2.6 on 2026-03-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_total_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
