# Generated by Django 5.2.6 on 2026-03-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_monthly_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
